Add commit restriction

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,3 +3,13 @@
 
 npm run lint
 npm test
+
+branch="$(git rev-parse --abbrev-ref HEAD)"
+if [ "$branch" = "master" ]; then
+  echo "You can't push directly to master branch"
+  exit 1
+fi
+if [ "$branch" = "main" ]; then
+  echo "You can't push directly to master branch"
+  exit 1
+fi
